version: "3.3"

services:
  db:
    image: naiades_watering
    environment:
      - POSTGRES_DB=naiades_watering
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  migrate:
    image: eanagnostopoulou/naiades-watering-web
    command: python manage.py migrate --noinput
    environment:
        - POSTGRES_HOST=db
        - POSTGRES_DB=naiades_watering
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
  web:
    build: .
    image: eanagnostopoulou/naiades-watering-web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "${NAIADES_WATERING_PORT:-80}:8000"
    #expose:
     # - "80"
    environment:
        - POSTGRES_HOST=db
        - POSTGRES_DB=naiades_watering
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - migrate