version: "3.3"

services:
  watering_db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  watering_migrate:
    image: eanagnostopoulou/naiades-watering-web
    command: python manage.py migrate --noinput
    environment:
        - POSTGRES_HOST=watering_db
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    depends_on:
      - watering_db
  watering_web:
    build: .
    image: eanagnostopoulou/naiades-watering-web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "${NAIADES_WATERING_PORT:-80}:8000"
    #expose:
     # - "80"
    environment:
        - POSTGRES_HOST=watering_db
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    depends_on:
      - watering_db
      - watering_migrate