# Generated by Django 2.0 on 2020-12-23 14:42
import os

from django.conf import settings
from django.db import migrations, models


def create_default_user(_, __):
    from django.apps import apps

    User = apps.get_model('auth', 'User')

    default_username = os.environ.get('DEFAULT_USER_USERNAME', 'naiades_user')
    default_password = os.environ.get('DEFAULT_USER_PASSWORD', 'qweasd!@#')

    if not User.objects.filter(username=default_username).exists():
        user = User(username=default_username)
        user.set_password(default_password)
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watering', '0003_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='serialNumber',
            field=models.CharField(db_index=True, default='-', max_length=16),
            preserve_default=False,
        ),
        migrations.RunPython(create_default_user, reverse_code=lambda _, __: None),
    ]
